### ISSUE TITLE
Deprecate

### ISSUE THREAD

**Issue by phated** [gulpjs/glob-watcher#22]
We are using chokidar directly in gulp 4, so we should probably deprecate this library.

**Comment by contra** [comment]
@phated Do you have access on npm? I think we should hold off until we publish 4.0 since it will log deprecation warnings for everyone with 3.x installed

**Comment by phated** [comment]
@contra yeah, I have access.  I agree that it shouldn't be deprecated until 4.0 release

**Comment by phated** [comment]
Not going to deprecate this after all.  We needed an abstraction for gulp.watch to allow debouncing and queueing.

**Comment by dippas** [comment]
H  @phated , sorry if this thread is not the right one but couldn't find a better one without opening a new issue

I've been using gulp v4 for awhile, at the moment (4.0.2), but every time I install the dependencies on my package.json I get a few warnings of deprecation and upon further investigation I came across that one of them was related to this package which is still using chokidar 2.1.8 (a deprecated version, when the latest version is 3.4.0)

The warning screenshot:
![image](https://user-images.githubusercontent.com/10220287/84963114-66246900-b100-11ea-9629-e181b2f8fa2b.png)

The location of chokidar is at in my dependencies:
![image](https://user-images.githubusercontent.com/10220287/84963182-9409ad80-b100-11ea-9611-3f7a6a4c8ecc.png)

Is this accurate about the version? Can you guys update this or this is going to stay like this?

**Comment by phated** [comment]
@dippas https://github.com/gulpjs/glob-watcher/issues/55#issuecomment-617915471
