### ISSUE TITLE
Lodash deprecation warning on gulp install

### ISSUE THREAD

**Issue by SgtPooki** [gulpjs/glob-watcher#23]
[Beginning of dependency tree (link to your package.json) ](https://github.com/gulpjs/glob-watcher/blob/master/package.json#L14) 
[gaze@0.5.1 tag no longer exists, resolves to 0.5.2, which points to node-globule@0.1.0](https://github.com/shama/gaze/blob/v0.5.2/package.json#L31)
[Ultimate Cause in node-globule@0.1.0](https://github.com/cowboy/node-globule/blob/v0.1.0/package.json#L48)

You should point to [gaze@0.6.0](https://github.com/shama/gaze/blob/v0.6.0/package.json) or later to resolve this dependency error when installing your package.

**Comment by phated** [comment]
No. We've thoroughly discussed why we won't upgrade in other threads. Lodash was stupid to do this to their package.

**Comment by SgtPooki** [comment]
Can you share the information you've discussed? You're probably talking about https://github.com/gulpjs/glob-watcher/issues/10 which talks a tiny bit about gaze and what @shama is going to do to gaze to make it not break stuff anymore, but then the conversation closes. Any updates?

**Comment by contra** [comment]
@SgtPooki We don't use gaze anymore because it was abandoned and had serious performance and stability issues. We switched to chokidar a long time ago in 4.0.
