### ISSUE TITLE
unclear error: must provide pattern

### ISSUE THREAD

**Issue by tomByrer** [gulpjs/glob-watcher#26]
I had an [trailing empty array](http://stackoverflow.com/a/31578955/1324588) that caused an "Error: must provide pattern".  Fortunately my paths list was short enough to figure it out, though I wish a better gulpfile location was provided.

'Won't fix' is fine; posting here more for bug searches, & hope that future error codes would be more at least more location specific.

**Comment by contra** [comment]
@tomByrer PR for better error message?

**Comment by phated** [comment]
Which version of glob-watcher?  The newest version is just passing globs off to chokidar

**Comment by phated** [comment]
Closing this due to no response.
