### ISSUE TITLE
chokidar won't glob symlinks while gaze did

### ISSUE THREAD

**Issue by thetrevdev** [gulpjs/glob-watcher#27]
Thought it would be worthwhile pointing out that chokidar won't glob symlinks while gaze did.

https://github.com/paulmillr/chokidar/issues/419
https://github.com/paulmillr/chokidar/issues/530

If I have the paths:

```
origin
symlink-to-origin -> ./origin
```
I can watch `./symlink-to-origin/*` but I can't watch `./symlink-*/*`

**Comment by phated** [comment]
As you linked, it's a chokidar problem. Please bring it up with them.

**Comment by thetrevdev** [comment]
As you can see in the links above this has been an open issue for 9 months in chokidar.
I thought it was valuable to point out that by changing the libraries you depend on you have broken some use cases that worked previously.
Apparently you don't think that is valuable to draw attention to.

**Comment by phated** [comment]
That's the reason for a semver major release. Things get changed, possibly removed.
