### ISSUE TITLE
Is there a module that has immutable assignment and ignores nullish values?

### ISSUE THREAD

**Issue by phated** [gulpjs/glob-watcher#29]
I figured I'd just ask this here.  Is there a module that behaves like the usage of `lodash.assignWith` (at https://github.com/gulpjs/glob-watcher/blob/master/index.js#L24) but avoids having the empty object at the beginning (immutable) and ignores nullish values by default?  @jonschlinkert @contra maybe you know of some?

**Comment by phated** [comment]
I was looking at https://github.com/Raynos/xtend but it assigns nullish values :frowning_face:

**Comment by jonschlinkert** [comment]
Do you need the customizer function too (like what's supported by `_.assignWith`), or just a shallow clone method (like `xtend`, but where nullish values are ignored)?

I use https://github.com/jonschlinkert/extend-shallow, but you still would need to pass an empty object as the first arg to shallow clone.

**Comment by phated** [comment]
I'd prefer for both things to be baked in.  It doesn't seem like `extend-shallow` ignores nullish values.  `assignWith` was used so the nullish customizer could be added, I'd like a module that just does that by default.

**Comment by jonschlinkert** [comment]
It ignores nullish values, but yeah,  you'd still need to pass an empty object to shallow clone. 

```js
var extend = require('extend-shallow');
console.log(extend({}, null, {a: 'b'}, null, {c: 'd'}));
//=> {a : 'b', c: 'd'}
```

**Comment by phated** [comment]
Sorry, I meant nullish properties.  `extend({ a: 123 }, { a: null })`

**Comment by phated** [comment]
Haha, actually found that `object.defaults` is doing what I want (`== null`) so I'll be switching to that.  Submitted a PR for a nice-to-have feature.
