### ISSUE TITLE
unclear error: must provide pattern

### ISSUE THREAD

**Issue by sreeyashu** [gulpjs/glob-watcher#32]
caused an "Error: must provide pattern".

![capture](https://user-images.githubusercontent.com/4896372/27861341-c7777648-6180-11e7-936a-95ec024802f4.PNG)

Could you please help me in solving this issue

{
    "version": "0.01",
    "common": {
        "css": [
            "ui/assets/icons/style.css",
          "ui/css/core.css"
        ],
        "js": [
          "ui/plugins/jquery-2.2.3.js",
          "ui/utils/browser-check.js",
          "ui/plugins/slick.js",
          "ui/plugins/bootstrap.js",
          "ui/jquery/commons.js",
          "ui/molecules/main-navigation/main-navigation.js",
          "ui/utils/google-analytics.js",
          "ui/utils/touch-move.js",
          "ui/utils/utils.js"
        ]
    },
    "pages": {
        "concept-detail": {
            "css": [
                "ui/css/pages/concept-detail/concept-detail.css"
            ],
            "js": [
                "ui/molecules/accordion/accordion.js",
                "ui/pages/concept-detail/concept-detail.js"
            ],
            "contentCategoryType": "product"
        },
        "article-detail": {
            "css": [
                "ui/css/pages/article-detail/article-detail.css"
            ],
            "js": [
                "ui/pages/article-detail/article-detail.js",
                "ui/vendor-js/add-to-any.js"
            ],
            "contentCategoryType": "community"
        },
        "article-overview": {
            "css": [
                "ui/css/pages/article-overview/article-overview.css"
            ],
            "js": [
                "ui/molecules/related-article/related-article.js"
            ],
            "contentCategoryType": "community"
        },
        "techproduct-info": {
            "css": [
                "ui/css/pages/techproduct-info/techproduct-info.css"
            ],
            "js": [
                "ui/molecules/product-block/product-block.js"
            ],
            "contentCategoryType": "product"
        },
        "concept-overview": {
            "css": [
                "ui/css/pages/concept-overview/concept-overview.css"
            ],
            "js": [
                "ui/molecules/slider/slider.js"
            ],
            "contentCategoryType": "product"
        },
        "privacy-policy": {
            "css": [
                "ui/css/pages/privacy-policy/privacy-policy.css"
            ],
            "js": [ ],
            "contentCategoryType": "other"
        },
        "partners-details": {
            "css": [
                "ui/css/pages/partners-details/partners-details.css"
            ],
            "js": [ ],
            "contentCategoryType": "other"
        },
        "contact-us": {
            "css": [
                "ui/css/pages/contact-us/contact-us.css"
            ],
            "js": [
                "ui/molecules/accordion/accordion.js",
                "ui/utils/form-validation.js",
                "ui/molecules/contact-message/contact-message.js"
            ],
            "contentCategoryType": "help center"
        },
        "home": {
            "css": [
                "ui/css/pages/home/home.css"
            ],
            "js": [
                "ui/molecules/testimonial/testimonial.js",
                 "ui/molecules/discover/discover.js"
            ],
            "contentCategoryType": "homepage"
        },
        "faq": {
            "css": [
                "ui/css/pages/faq/faq.css"
            ],
            "js": [
                "ui/pages/faq/faq.js",
                "ui/molecules/accordion/accordion.js"
            ],
            "contentCategoryType": "help center"
        },
        "concrete-overview": {
            "css": [
                "ui/css/pages/concrete-overview/concrete-overview.css"
            ],
            "js": [ ],
            "contentCategoryType": "product"
        }
    }
}

**Comment by phated** [comment]
You aren't passing a glob string to your watcher.  Future support questions should be directed to StackOverflow.
