### ISSUE TITLE
Update the upath dependency: the current version is not compatible with node >=10

### ISSUE THREAD

**Issue by wujekbogdan** [gulpjs/glob-watcher#37]
[upath](https://github.com/anodynos/upath) - the module that glob-watcher depends on has the following setting specified in package.json:

```
"engines": {
    "node": ">=4 <=9"
  },
```

This setting prevents it from being installed when the local version of node is newer than 9.  This problem has been fixed already in upath v1.0.5, so please update your `package.json`

Thanks.

**Comment by contra** [comment]
Not a direct dependency of ours - this will get pulled in automatically, just run `npm update`.

**Comment by wujekbogdan** [comment]
> Not a direct dependency of ours - this will get pulled in automatically

True. My bad. I didn't notice it's a dependency of chokidar.

> just run npm update.

Or `yarn upgrade` :)
