### ISSUE TITLE
Unnecessary restarts on Windows due to old chokidar bug (since fixed)

### ISSUE THREAD

**Issue by mikemaccana** [gulpjs/glob-watcher#44]
See https://github.com/paulmillr/chokidar/pull/762

Just update chokidar.

**Comment by mikemaccana** [comment]
PS. gulp should update it's dependency on glob-watcher once this is in a new glob-watcher.

**Comment by phated** [comment]
@mikemaccana If that landed in 3, it breaks our compatibility matrix. I can probably start on a version of this module that will be a major but it can't get upstreamed into gulp for awhile.

**Comment by mikemaccana** [comment]
@phated It;s in the latest v2.

**Comment by phated** [comment]
Then you can just remove your package-lock and update. We use ^2 semver.

**Comment by phated** [comment]
Closing, as semver should solve this.
