### ISSUE TITLE
Future: Update chokidar

### ISSUE THREAD

**Issue by pronebird** [gulpjs/glob-watcher#49]
Hi,

Could you please update `chokidar` to 3.x. It's been a couple of years and it seems that `fsevents` used by `chokidar` 2.x is broken when compiled against the newer Node APIs (v12.x). However that has to be fixed in newer `chokidar` and `fsevents`.

**Comment by phated** [comment]
See #41 #42 #47 #48 - we have a version matrix that doesn't work with chokidar 3.x - when those versions are dropped, we will upgrade.

**Comment by pronebird** [comment]
Sorry for duping this. I've looked through issues but not PRs.

Welp that's unfortunate that gulp uses external dependencies given its commitment to support node 0.10. It means we're all stuck on broken software full of security flaws. Amazing.

**Comment by nicolashenry** [comment]
I asked when 0.10/0.12 node version support will be dropped for gulpjs packages [here](https://github.com/gulpjs/gulp/issues/1829#issuecomment-608108858) but in view of the answer it seems that it is not likely to happen soon.
