### ISSUE TITLE
Upgrade chokidar for real. v2 will break on node 14

### ISSUE THREAD

**Issue by paulmillr** [gulpjs/glob-watcher#55]
Hey @phated and folks,

We've released Chokidar 3 one year ago. See my post on that: [Chokidar 3: How to save 32TB of traffic every week with one NPM package](https://paulmillr.com/posts/chokidar-3-save-32tb-of-traffic/)

The changes are pretty big. First of all, the package is 16 times smaller and uses 15 dependencies instead of 201. We've switched to n-api, which means users won't download fsevents binaries anymore. n-api is included in every nodejs installation, and it's tiny. Directory walking has been improved massively with stream implementation of readdirp. Massive RAM & CPU improvements etc.

*I saw previous issues* (#41 #42 #47 #48 #49 etc), but unfortunately they're either closed or closed for comments. I think it's time to drop old versions from the build matrix. Not doing so **will break** `gulpjs/glob-watcher` fsevents watching on nodejs 14+.

**Comment by phated** [comment]
Yep, it's on the roadmap but the team is underfunded and overworked so it will happen when it happens. 🤷

The goal is to support either node 12+ or 14+ when development begins on gulp 5, but again, no idea when that will be.

**Comment by paulmillr** [comment]
>the team is underfunded and overworked

Same thing here. No one pays us at all.

What do you think about an idea of releasing gulp 5 with gulp4 codebase & node 12/14 requirement / updated chokidar? This decision alone will be great for the future. It will also improve gulp installation time massively.

**Comment by phated** [comment]
> Same thing here. No one pays us at all.

I've actually been meaning to reach out about that. Tidelift has some money available for Chokidar: https://tidelift.com/lifter/search/npm/chokidar - I could get you set up if you'd like.

> What do you think about an idea of releasing gulp 5 with gulp4 codebase & node 12/14 requirement / updated chokidar? This decision alone will be great for the future. It will also improve gulp installation time massively.

It's not just this library that needs to be upgraded. It'd probably be hundreds of hours to update the >100 repositories I maintain for gulp.

**Comment by paulmillr** [comment]
Got it. 

>Tidelift has some money available for Chokidar

That seems interesting. Would I need to work on some user issues after the tidelift account is created?

**Comment by phated** [comment]
> Got it.

I'm discussing the plan with the rest of the gulp team. We'll see if we can do something but I can't commit to anything right now.

> Would I need to work on some user issues after the tidelift account is created?

There's a subcontractor agreement that I put in place, then a handful of setup tasks that usually take ~1 hour to set up. We currently don't have user issues integrated into the platform, so it's mostly just metadata stuff (license, changelog, etc).

**Comment by paulmillr** [comment]
Please ping me via paul at paulmillr.com, let's set up this.

**Comment by MylesBorins** [comment]
This is now broken on Node.js 12 as well

**Comment by mahnunchik** [comment]
Any news?
