### ISSUE TITLE
Test suite consistently failing on Node.js 12 and 14

### ISSUE THREAD

**Issue by MylesBorins** [gulpjs/glob-watcher#58]
This fails with a variety of abort traps. It would appear that the source of the issue in the old version of chokidar

**Comment by phated** [comment]
Very weird to be introducing major breaking changes in an LTS version of the platform.

**Comment by MylesBorins** [comment]
I'm tracking down exactly what is going on... but afaict the change is breaking the unmaintained version of chokidar v1 and fsevents v1.

**Comment by MylesBorins** [comment]
So looking at it right now it seems like the change that broke the test suite landed in 12.18.2, which only had two changes... both related to fixing pretty bad memory leaks, and neither of which appear on surface to be Semver-Major

**Comment by MylesBorins** [comment]
https://github.com/nodejs/node/pull/34077

**Comment by MylesBorins** [comment]
So it would appear that this is the change that introduced the breakages on 12.x

https://github.com/nodejs/node/commit/6f6bf010a7bfde32f4015758ae2f2af8b45cb612

FWIW there are still unreliable segmentation faults on v14.x with glob-watcher before this change landed. While it is creating reliable failures with glob-watcher on 12.x, those failures only exist when using an old, unsupported, version of a dependency (chokidar). While I can see how this can be seen as a "Major Breaking Change" I really don't think it is right to categorize it that way as the dependencies you are relying on explicitly do not support more modern versions of node.

It would appear, although it is not totally obvious yet, that there are existing underlying bugs we are dealing with here that are being unearthed by these changes. Since this change is effectively fixing a rather serious memory leak on 12.x, I doubt that we are going to be looking at reverting it.

The change that landed on 14.x, that also causes similar breakages, is similarly a non-breaking change... but rather a change to internals.
