### ISSUE TITLE
watch still does not support ignored glob

### ISSUE THREAD

**Issue by slashhuang** [gulpjs/glob-watcher#62]
in your source code, although file is excluded by `negativeMatch > positiveMatch`。
watch task still run。。

**Comment by phated** [comment]
This was recently changed (fixed) and published. You can see the tests were added as well. It is likely you are using a lockfile that has an old version of glob-watcher pinned and you need to update.

**Comment by slashhuang** [comment]
@phated  thanks, i just updated the package,5.0.5 works for me, problem lies on lock file

**Comment by slashhuang** [comment]
just figure out that，glob like `./**/*` will wrongly normalized to `cwd/./**/*`，solved by change `./**/*`  to `**/*`，thank 
you。 5.0.5 glob-watch solved negative issue
