### ISSUE TITLE
What is your support policy for unsupported versions of Node?

### ISSUE THREAD

**Issue by Flimm** [gulpjs/glob-watcher#70]
Hello. I am wondering what your policy is, when you will drop support for older versions of Node. Currently, some issues are not being fixed because the maintainers want to maintain support for Node 0.10. Node 0.10.0 was released in March 2013. It hasn't been a supported version of Node for years. The oldest version of Node which is still currently supported is Node 12.0 . Have [a look at Node's support schedule](https://nodejs.org/en/about/releases/).

Now, I realise the maintainers of `glob-watcher` may want to support old versions of Node that aren't supported by Node themselves. However, I am interested in knowing what your support policy is. Are you going to be supporting Node 0.10 forever? When will you consider dropping support for it?

Knowing the answers to these questions will help me understand what the intended use-cases for `glob-watcher` are, and will help me decide whether to include `glob-watcher` as a dependency in my projects or not. If the current plan is to continue supporting Node 0.10, it would be helpful if that were documented in the README. Thank you!

**Comment by phated** [comment]
It's happening now. It's a massive undertaking. It'll be released as v5 when done.

**Comment by Flimm** [comment]
Hi @phated . Help me understand your comment. What will be relased when v5 is done? `glob-watcher` is already at version 5.0.5.

**Comment by phated** [comment]
Don't use this library, it is only for use in gulp internals. The v5 I'm referring to is gulp.
