### ISSUE TITLE
Updating chokidar npm package

### ISSUE THREAD

**Issue by jdcoldsmith** [gulpjs/glob-watcher#74]
Hello,

I just wanted to poke this issue and possibly get an explanation as to why chokidar has not been upgraded since it currently results in a 
high npm security vulnerability?

![image](https://user-images.githubusercontent.com/65235172/160476370-3ba80c03-bd2d-43a5-8f2b-920b09dd7f48.png)

Thanks for you help!

**Comment by phated** [comment]
It is a semver breaking change. We are working on v5 currently.

This issue doesn't affect build tools.
